# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='favourites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Favourites'),
        ),
    ]
